library(tidyverse)

# Set working directory
setwd(glue::glue("{dirname(rstudioapi::getActiveDocumentContext()$path)}/.."))

# read data generated by Tim C. and Chido C. in 2018. These data were generated with the ct program installed on Tim C.'s work computer with the notes/work__init__.py and notes/work_command.py scripts
df <- as.data.frame(read.csv(file = glue::glue("data/Results_Block_3_4_6b_8.csv"), header = T)) %>%
  dplyr::select(-X, -X.1, -X.2) %>%
  dplyr::filter(CI != "#DIV/0!") %>%
  dplyr::filter(strain != "ED3017") %>%
  dplyr::filter(!is.na(Assay),
                Assay != "20180307") %>% #filter block 20180307
  dplyr::mutate(CI = as.numeric(as.character(CI)),
                drug = ifelse(drug == "isa", "isoamly alcohol", "1-octanol"))

# get the treatments
treat <- df %>%
  dplyr::filter(counter == "auto") %>%
  dplyr::select(Assay, Image_ID, strain, drug)

#=====================================================#
# Get new ct results
#=====================================================#
# read in data generated with ct python package in AndersenLab/chemotaxis-cli github repo.
r <- list("data/20220331_20180321_crop_results.txt", "data/20220331_20180420_crop_results.txt", "data/20220331_20180508_crop_results.txt")
df_ct <-purrr::map_dfr(r, function(x) {
  data.table::fread(file = x) %>%
    dplyr::mutate(Assay = as.integer(stringr::str_extract(x, pattern = "(?<=_)([0-9]+)"))) %>% # look behind _ and get number string
    dplyr::rename(Image_ID = fname)
})
  
df_comp<- df_ct %>%
  dplyr::select(Assay, Image_ID, ci) %>%
  dplyr::left_join(df) %>%
  dplyr::mutate(ci_diff = ifelse(counter == "auto", CI-ci, NA_real_))

# plot diff between old auto CI measurements and new CI measurements.
diff_dist <- df_comp %>%
  dplyr::filter(counter == "auto") %>%
  ggplot2::ggplot() +
  ggplot2::aes(x = ci_diff) +
  ggplot2::geom_histogram(bins = 60) +
  labs(x = "CI diff (work - repo:ae48a5c)") +
  ggplot2::xlim(-1, 1)
diff_dist

#==================================================#
# plot comparison with manual
#==================================================#
cor_new <- df_comp %>%
  dplyr::mutate(CI = case_when(counter == "auto" ~ ci,
                               counter != "auto" ~ CI)) %>%
  dplyr::select(-ci, -ci_diff)

# Shape data to fit lm with ggplot::geom_smooth to manual counts vs. automated counts
df_corr <- cor_new %>%
  dplyr::select(-Drug_Count, -Control_Count, -count) %>%
  dplyr::filter(!is.na(CI)) %>%
  tidyr::spread(counter, CI) %>% 
  dplyr::rename(man_ci = manual, auto_ci = auto)
  
# Plot the correlation between methods
corr <- ggplot2::ggplot(df_corr) +
  ggplot2::aes(x = man_ci, y = auto_ci) +
  ggplot2::geom_point(aes(x = man_ci, y = auto_ci, color = as.factor(drug))) + 
  ggplot2::geom_abline(intercept = 0, slope = 1, linetype = 2) +
  ggplot2::geom_smooth(method=lm, size = 0.5, se = F) +
  ggpubr::stat_regline_equation(label.y = 0.75, aes(label = ..eq.label..)) +
  ggpubr::stat_regline_equation(label.y = 0.5, aes(label = ..rr.label..)) +
  ggplot2::xlim(-1,1) +
  ggplot2::ylim(-1,1) +
  theme_bw() +
  ggplot2::labs(title = "", color = "compound", x = "Manual (CI)", y = "Automated (CI)") +
  ggplot2::theme(legend.position= c(0.8, 0.2))
corr

# double check ggplot::geom_smooth calculated correct lm and r^2
cor(df_corr %>% tidyr::drop_na(.) %>% dplyr::pull("auto_ci"), df_corr %>% tidyr::drop_na(.) %>% dplyr::pull("man_ci"))^2
lm(df_corr %>% tidyr::drop_na(.) %>% dplyr::pull("auto_ci") ~ df_corr %>% tidyr::drop_na(.) %>% dplyr::pull("man_ci"))

# save the correlation plot
cowplot::ggsave2(corr, filename = 'plots/assay_agreement_CI_updated_ct.png', width = 3.5, height = 3.5)
