library(tidyverse)

# Set working directory
setwd(glue::glue("{dirname(rstudioapi::getActiveDocumentContext()$path)}/.."))

# read data generated by Tim C. and Chido C. in 2018. These data were generated with the ct program installed on Tim C.'s work computer with the notes/work__init__.py and notes/work_command.py scripts
df <- as.data.frame(read.csv(file = glue::glue("data/Results_Block_3_4_6b_8.csv"), header = T)) %>%
  dplyr::select(-X, -X.1, -X.2) %>%
  dplyr::filter(CI != "#DIV/0!") %>%
  dplyr::filter(strain != "ED3017") %>%
  dplyr::filter(!is.na(Assay),
                Assay != "20180307") %>% #filter block 20180307
  dplyr::mutate(CI = as.numeric(as.character(CI)),
                drug = ifelse(drug == "isa", "isoamly alcohol", "1-octanol"))

#=====================================================#
# Get new ct results
#=====================================================#
# read in data generated with ct python package in AndersenLab/chemotaxis-cli github repo.
r <- list("data/20220331_20180321_crop_results.txt", "data/20220331_20180420_crop_results.txt", "data/20220331_20180508_crop_results.txt")
df_ct <-purrr::map_dfr(r, function(x) {
  data.table::fread(file = x) %>%
    dplyr::mutate(Assay = as.integer(stringr::str_extract(x, pattern = "(?<=_)([0-9]+)"))) %>% # look behind _ and get number string
    dplyr::rename(Image_ID = fname)
})

df_comp<- df_ct %>%
  dplyr::select(Assay, Image_ID, ci) %>%
  dplyr::left_join(df) %>%
  dplyr::mutate(ci_diff = ifelse(counter == "auto", CI-ci, NA_real_))

# plot diff between old auto CI measurements and new CI measurements.
diff_dist <- df_comp %>%
  dplyr::filter(counter == "auto") %>%
  ggplot2::ggplot() +
  ggplot2::aes(x = ci_diff) +
  ggplot2::geom_histogram(bins = 60) +
  labs(x = "CI diff (work - repo:ae48a5c)") +
  ggplot2::xlim(-1, 1)
diff_dist

#==================================================#
# plot comparison with manual
#==================================================#
cor_new <- df_comp %>%
  dplyr::mutate(CI = case_when(counter == "auto" ~ ci,
                               counter != "auto" ~ CI)) %>%
  dplyr::select(-ci, -ci_diff)

# Shape data to fit lm with ggplot::geom_smooth to manual counts vs. automated counts
df_corr <- cor_new %>%
  dplyr::select(-Drug_Count, -Control_Count, -count) %>%
  dplyr::filter(!is.na(CI)) %>%
  tidyr::spread(counter, CI) %>% 
  dplyr::rename(man_ci = manual, auto_ci = auto)

# Plot the correlation between methods
corr <- ggplot2::ggplot(df_corr) +
  ggplot2::aes(x = man_ci, y = auto_ci) +
  ggplot2::geom_point(aes(x = man_ci, y = auto_ci, color = as.factor(drug))) + 
  ggplot2::geom_abline(intercept = 0, slope = 1, linetype = 2) +
  ggplot2::geom_smooth(method=lm, size = 0.5, se = F) +
  ggpubr::stat_regline_equation(label.y = 0.75, aes(label = ..eq.label..)) +
  ggpubr::stat_regline_equation(label.y = 0.5, aes(label = ..rr.label..)) +
  ggplot2::xlim(-1,1) +
  ggplot2::ylim(-1,1) +
  theme_bw() +
  ggplot2::labs(title = "", color = "compound", x = "Manual (CI)", y = "Automated (CI)") +
  ggplot2::theme(legend.position= c(0.8, 0.2))
corr

# double check ggplot::geom_smooth calculated correct lm and R^2
cor(df_corr %>% tidyr::drop_na(.) %>% dplyr::pull("auto_ci"), df_corr %>% tidyr::drop_na(.) %>% dplyr::pull("man_ci"))^2
lm <- lm(df_corr %>% tidyr::drop_na(.) %>% dplyr::pull("auto_ci") ~ df_corr %>% tidyr::drop_na(.) %>% dplyr::pull("man_ci"))
summary(lm)$r.squared 

# save the correlation plot
cowplot::ggsave2(corr, filename = 'plots/assay_agreement_CI_updated_ct.png', width = 3.5, height = 3.5)

#==================================================#
# UPDATE CORR FOR EACH TYPE
#==================================================#

corr_v2 <- ggplot() +
  geom_point(data = df_corr %>% dplyr::filter( drug == "1-octanol"), aes(x = man_ci, y = auto_ci, fill = as.factor(drug)), shape = 21) +
  geom_smooth(data = df_corr %>% dplyr::filter(drug == "1-octanol"), aes(x = man_ci, y = auto_ci), method="lm", color = "#F8766D", size = 0.5) +
  ggpubr::stat_regline_equation(data = df_corr %>% dplyr::filter( drug == "1-octanol"), label.y = 0.75, label.x = -1, color = "#F8766D", aes(x = man_ci, y = auto_ci, label = ..eq.label..)) +
  ggpubr::stat_regline_equation(data = df_corr %>% dplyr::filter( drug == "1-octanol"), label.y = 0.75, label.x = -0.4, color = "#F8766D", aes(x = man_ci, y = auto_ci, label = ..rr.label..)) +
  geom_point(data = df_corr %>% dplyr::filter( drug == "isoamly alcohol"), aes(x = man_ci, y = auto_ci, fill = as.factor(drug)), shape = 21) +
  geom_smooth(data = df_corr %>% dplyr::filter(drug == "isoamly alcohol"), aes(x = man_ci, y = auto_ci), method="lm", color = "#00BFC4", size = 0.5) +
  ggpubr::stat_regline_equation(data = df_corr %>% dplyr::filter( drug == "isoamly alcohol"), label.y = 1, label.x = -1, color = "#00BFC4", aes(x = man_ci, y = auto_ci, label = ..eq.label.., color = "#F8766D")) +
  ggpubr::stat_regline_equation(data = df_corr %>% dplyr::filter( drug == "isoamly alcohol"), label.y = 1, label.x = -0.4, color = "#00BFC4", aes(x = man_ci, y = auto_ci, label = ..rr.label.., color = "#F8766D")) +
  ggplot2::geom_abline(intercept = 0, slope = 1, linetype = 2) +
  xlim(-1,1) +
  ylim(-1,1) +
  ggplot2::labs(title = "", fill = "compound", x = "Manual (CI)", y = "Automated (CI)") +
  ggplot2::theme_bw() +
  ggplot2::theme(legend.position= c(0.8, 0.2),
                 panel.grid.major = element_blank(),
                 panel.grid.minor = element_blank())
corr_v2

# save the updated correlation plot
cowplot::ggsave2(corr_v2, filename = 'plots/assay_agreement_CI_updated_ct_v2.png', width = 3.65, height = 3.65)
cowplot::ggsave2(corr_v2, filename = 'plots/assay_agreement_CI_updated_ct_v2.pdf', width = 3.65, height = 3.65)

#========================================================#
# Heritability 
#========================================================#
# Shape data to calculate heritability including three replicates per block
h2_df_assay <- cor_new %>%
  dplyr::rename(trait = drug, value = CI) %>%
  dplyr::select(-Drug_Count, -Control_Count, -Image_ID) %>% 
  dplyr::mutate(strain = as.character(strain)) %>%
  dplyr::arrange(counter, trait, strain) %>%
  dplyr::group_by(trait, counter, strain, Assay) %>%
  dplyr::mutate(value2 = mean(value)) %>%
  dplyr::ungroup()

# Source heritability functions
source("scripts/heritability_functions.R")

# heritability caluculations
oct_H2_auto <- H2.bootstrapping.calc(h2_df_assay %>% dplyr::filter(trait == "1-octanol" & counter == "auto") %>% dplyr::select(strain, value))
oct_H2_man <- H2.bootstrapping.calc(h2_df_assay %>% dplyr::filter(trait == "1-octanol" & counter == "manual") %>% dplyr::select(strain, value))
iso_H2_auto <- H2.bootstrapping.calc(h2_df_assay %>% dplyr::filter(trait == "isoamly alcohol" & counter == "auto") %>% dplyr::select(strain, value))
iso_H2_manual <- H2.bootstrapping.calc(h2_df_assay %>% dplyr::filter(trait == "isoamly alcohol" & counter == "manual") %>% dplyr::select(strain, value))

# Build heritability summary dataframe
h2_dat <- tibble::tibble(type = c("oct_h2_auto","oct_H2_man","iso_H2_auto","iso_H2_man"), dplyr::bind_rows(oct_H2_auto[[1]], oct_H2_man[[1]], iso_H2_auto[[1]], iso_H2_manual[[1]])) %>%
  tidyr::separate(type, into = c("drug", "type", "counter"))

# plot hetitability
h2_plot <- ggplot(h2_dat %>%
                    dplyr::mutate(drug = ifelse(drug == "oct", "1-octanol", "isoamly alcohol")) %>%
                    dplyr::mutate(counter = ifelse(counter == "auto", "Automated", "Manual"))) +
  geom_point(aes(x = counter, y = H2.Point.Estimate), size = 3) +
  geom_errorbar(aes(ymin=H2.5.perc, ymax=H2.95.perc, x = counter), colour="black", width=0.05) +
  labs(x = "", y = "Broad-sense heritability") +
  ylim(0, 1) +
  theme_bw()+
  facet_grid(~drug) +
  geom_hline(yintercept = .2, color= "black", lty = 2) +
  ggplot2::theme(panel.grid.major = element_blank(),
                 panel.grid.minor = element_blank())
h2_plot

# save heritability plot
cowplot::ggsave2(h2_plot, filename = "plots/heritability.png", width = 3.5, height = 3.5)

#=====================================================#
# Combine corr and h2 plots
#=====================================================#
cor_h2_plot <- cowplot::plot_grid(corr_v2, h2_plot, align = "hv", axis = "lrtb")

cowplot::ggsave2(cor_h2_plot, filename = "plots/corr_h2_plot.pdf", width = 7.25, height = 3.625)
#=====================================================#
# make map of all isotypes
#=====================================================#
# read ce sp sheet
ce <- gsheet::gsheet2tbl(url = "https://docs.google.com/spreadsheets/d/10x-CcKNCl80F9hMcrGWC4fhP_cbekSzi5_IYBY2UqCc/edit#gid=538533765") 

# process the species sheet
ce_proc <- ce %>%
  dplyr::filter(!is.na(latitude) & strain == isotype) %>%
  #dplyr::distinct(isotype, latitude, longitude, .keep_all = T) %>%
  dplyr::mutate(color = case_when(strain %in% df$strain ~ "used",
                                  !(strain %in% df$strain) ~ "not_used"))

# get an sf world map object from rnaturalearth package and dump antartica
world <- rnaturalearth::ne_countries(scale = "medium", returnclass = "sf") %>%
  dplyr::filter(geounit != "Antarctica")

# make ce_proc into an sf object with same crs as world map
ce_proc_sf <- sf::st_as_sf(ce_proc, coords = c("longitude", "latitude"), crs = sf::st_crs(world))

# plot the map with labels for our strains
map <- ggplot2::ggplot() +
  ggplot2::geom_sf(data = world, fill = "white", lwd = 0.15) +
  ggthemes::theme_map() +
  ggplot2::theme(legend.position = "none") +
  geom_sf(data = ce_proc_sf, aes(fill = color), size = 1.75, stroke = 0.15, shape = 21, color = "grey8", alpha = 1) +
  ggplot2::scale_fill_manual(values = c("lightgrey", "red")) +
  ggrepel::geom_label_repel(
    data = ce_proc_sf %>% dplyr::filter(strain %in% df$strain),
    aes(label = isotype, geometry = geometry),
    stat = "sf_coordinates",
    min.segment.length = 0,
    colour = "grey8",
    segment.colour = "grey8",
    size = 2.5, label.padding = 0.1, stroke = 0.15)

# save the map
cowplot::ggsave2(map, filename = "plots/map.pdf", width = 4.6, height = 3.625)

#=====================================================#
# Update E to per strain lm fit
#=====================================================#
# strain effect plot
ggplot(df_corr) +
  aes(x = man_ci, y = auto_ci, group = strain, color = strain) +
  geom_smooth(method="lm", size = 0.5, ) +
  ggpubr::stat_regline_equation(aes(label = ..eq.label..)) +
  xlim(-1,1) +
  ylim(-1,1) +
  ggplot2::geom_abline(intercept = 0, slope = 1, linetype = 2) +
  ggplot2::labs(title = "", color = "strain", x = "Manual (CI)", y = "Automated (CI)") +
  ggplot2::theme_bw() +
  ggplot2::theme(legend.position= c(0.8, 0.2),
                 panel.grid.major = element_blank(),
                 panel.grid.minor = element_blank())

# add slope and intercept estimates from each assay aross both compounds
df_E <- df_corr %>%
  dplyr::group_by(Assay, strain) %>%
  dplyr::mutate(intercept = lm(auto_ci ~ man_ci)[[1]][1],
                slope = lm(auto_ci ~ man_ci)[[1]][2],
                n = n()) %>%
  dplyr::group_by(strain) %>%
  dplyr::mutate(mean_int = mean(intercept),
                mean_slope = mean(slope),
                max_int = max(intercept),
                min_int = min(intercept),
                max_slope = max(slope),
                min_slope = min(slope)) %>%
  dplyr::ungroup()

# plot box plot for each strain
int_plot <- ggplot2::ggplot(df_E %>% dplyr::distinct(strain, .keep_all = T)) +
  ggplot2::aes(x = as.factor(strain), y = mean_int) +
  #ggplot2::geom_point(shape = 1) +
  ggplot2::geom_pointrange(aes(ymin=min_int, ymax=max_int)) +
  ggplot2::geom_abline(intercept = 0, slope = 0, linetype = 2) +
  ggplot2::labs(title = "", color = "strain", x = "", y = "intercept") +
  ggplot2::theme_bw() +
  ggplot2::theme(legend.position= "none",
                 axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1),
                 panel.grid.major = element_blank(),
                 panel.grid.minor = element_blank())

slope_plot <- ggplot2::ggplot(df_E %>% dplyr::distinct(strain, .keep_all = T)) +
  ggplot2::aes(x = as.factor(strain), y = mean_slope) +
  #ggplot2::geom_point(shape = 1) +
  ggplot2::geom_pointrange(aes(ymin=min_slope, ymax=max_slope)) +
  ggplot2::geom_abline(intercept = 1, slope = 0, linetype = 2) +
  ggplot2::labs(title = "", color = "strain", x = "", y = "slope") +
  ggplot2::theme_bw() +
  ggplot2::theme(legend.position= "none",
                 axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1),
                 panel.grid.major = element_blank(),
                 panel.grid.minor = element_blank())
  
E2 <- cowplot::plot_grid(int_plot, slope_plot, ncol = 1, align = "vh")
E2  

cowplot::ggsave2(E2, filename = "plots/model_coef_plot.pdf", width = 3.6, height = 4.8)

# test for an effect of strain on lm parameters
e2m_int <- lm(data = df_E %>% dplyr::distinct(Assay, strain, .keep_all = T), formula = intercept ~ strain)
anova(e2m_int)

e2m_slope <- lm(data = df_E %>% dplyr::distinct(Assay, strain, .keep_all = T), formula = slope ~ strain)
anova(e2m_slope)

# test power from our data - https://aaroncaldwell.us/SuperpowerBook/index.html#preface
test <- lm(data = df_E, formula = auto_ci ~ man_ci + strain + as.character(Assay))
anova(test)


