library(tidyverse)

# Set working directory
setwd(glue::glue("{dirname(rstudioapi::getActiveDocumentContext()$path)}/.."))

# read data generated by Tim C. and Chido C. in 2018. These data were generated with the ct program installed on Tim C.'s work computer with the notes/work__init__.py and notes/work_command.py scripts
df <- as.data.frame(read.csv(file = glue::glue("data/Results_Block_3_4_6b_8.csv"), header = T)) %>%
  dplyr::select(-X, -X.1, -X.2) %>%
  dplyr::filter(CI != "#DIV/0!") %>%
  dplyr::filter(strain != "ED3017") %>%
  dplyr::filter(!is.na(Assay),
                Assay != "20180307") %>% #filter block 20180307
  dplyr::mutate(CI = as.numeric(as.character(CI)),
                drug = ifelse(drug == "isa", "isoamly alcohol", "1-octanol"))

# read in test data generated with __init__.py and command.py scripts in AndersenLab/chemotaxis-cli github repo
# Data made with repo commit = ae48a5c from Mar 13, 2017
test <- 